version: "3.9" # optional since v1.27.0

services:
  nvim:
    image: zane/nvchad
    ports:
      - "3333:3333"
      - "4000:4000"
      - "5000:5000"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - c:\a:/home/nv/a
      - c:\Users\zane_\.ssh:/home/nv/.ssh
      - //var/run/docker.sock:/var/run/docker.sock
      - nvim_red_duck:/home/nv/nvim_red_duck

volumes:
  nvim_red_duck:
    external: true
